services:
  - type: web
    name: flask-poetry-kitemongerer
    runtime: python
    plan: starter
    buildCommand: poetry install
    startCommand: gunicorn app:app --chdir ./poetry_flask
    autoDeploy: false
